/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionEvent;

/**
 *
 * @author SPA Grupo16
 */
public class SpaRelax extends javax.swing.JFrame {

    /**
     * Creates new form SpaRelax
     */
    public SpaRelax() {
        initComponents();
        setExtendedState(SpaRelax.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCliente = new javax.swing.JMenu();
        cliente = new javax.swing.JMenuItem();
        menMasajista = new javax.swing.JMenu();
        masajista = new javax.swing.JMenuItem();
        menTratamiento = new javax.swing.JMenu();
        tratamiento = new javax.swing.JMenuItem();
        menConsultorios = new javax.swing.JMenu();
        consultorios = new javax.swing.JMenuItem();
        menInstalacion = new javax.swing.JMenu();
        instalacion = new javax.swing.JMenuItem();
        menSesion = new javax.swing.JMenu();
        formSesion = new javax.swing.JMenuItem();
        menDiaDeSpa = new javax.swing.JMenu();
        mItemDiaSpa = new javax.swing.JMenuItem();
        menListados = new javax.swing.JMenu();
        mnuItemListados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPA Relax \"Entre Dedos\"");

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        menCliente.setText("Cliente");

        cliente.setText("Clientes");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        menCliente.add(cliente);

        jMenuBar1.add(menCliente);

        menMasajista.setText("Masajista");

        masajista.setText("Masajistas");
        masajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masajistaActionPerformed(evt);
            }
        });
        menMasajista.add(masajista);

        jMenuBar1.add(menMasajista);

        menTratamiento.setText("Tratamiento");
        menTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menTratamientoActionPerformed(evt);
            }
        });

        tratamiento.setText("Tratamientos");
        tratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamientoActionPerformed(evt);
            }
        });
        menTratamiento.add(tratamiento);

        jMenuBar1.add(menTratamiento);

        menConsultorios.setText("Consultorio");

        consultorios.setText("Consultorios");
        consultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultoriosActionPerformed(evt);
            }
        });
        menConsultorios.add(consultorios);

        jMenuBar1.add(menConsultorios);

        menInstalacion.setText("Instalacion");

        instalacion.setText("Instalaciones");
        instalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instalacionActionPerformed(evt);
            }
        });
        menInstalacion.add(instalacion);

        jMenuBar1.add(menInstalacion);

        menSesion.setText("Sesión");

        formSesion.setText("Form. Sesión");
        formSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formSesionActionPerformed(evt);
            }
        });
        menSesion.add(formSesion);

        jMenuBar1.add(menSesion);

        menDiaDeSpa.setText("Dia de Spa");

        mItemDiaSpa.setText("Form. Dia de Spa");
        mItemDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDiaSpaActionPerformed(evt);
            }
        });
        menDiaDeSpa.add(mItemDiaSpa);

        jMenuBar1.add(menDiaDeSpa);

        menListados.setText("Listados");

        mnuItemListados.setText("Ver listados");
        mnuItemListados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemListadosActionPerformed(evt);
            }
        });
        menListados.add(mnuItemListados);

        jMenuBar1.add(menListados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDiaSpaActionPerformed
        VistaDiaDeSpa diaDeSpa = new VistaDiaDeSpa();
        jDesktop.add(diaDeSpa);
        diaDeSpa.setVisible(true);
        centrarVentana(diaDeSpa);
    }//GEN-LAST:event_mItemDiaSpaActionPerformed

    private void formSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formSesionActionPerformed
        VistaSesion sesion = new VistaSesion();
        jDesktop.add(sesion);
        sesion.setVisible(true);
        centrarVentana(sesion);
    }//GEN-LAST:event_formSesionActionPerformed

    private void instalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instalacionActionPerformed
        VistaInstalacion instalacion = new VistaInstalacion();
        jDesktop.add(instalacion);
        instalacion.setVisible(true);
        centrarVentana(instalacion);
    }//GEN-LAST:event_instalacionActionPerformed

    private void menTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menTratamientoActionPerformed


    }//GEN-LAST:event_menTratamientoActionPerformed

    private void tratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamientoActionPerformed
        // TODO add your handling code here:

        VistaTratamiento vistaT = new VistaTratamiento();
        jDesktop.add(vistaT);
        vistaT.setVisible(true);
        centrarVentana(vistaT);
    }//GEN-LAST:event_tratamientoActionPerformed

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void consultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultoriosActionPerformed
        VistaConsultorio vistaC = new VistaConsultorio();

        jDesktop.add(vistaC);
        vistaC.setVisible(true);
        centrarVentana(vistaC);
        vistaC.toFront();
    }//GEN-LAST:event_consultoriosActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        VistaCliente vistac = new VistaCliente();
        jDesktop.add(vistac);
        vistac.setVisible(true);
        centrarVentana(vistac);
        vistac.toFront();


    }//GEN-LAST:event_clienteActionPerformed

    private void mnuItemListadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemListadosActionPerformed
        VistaListados vistaListas = new VistaListados();
        jDesktop.add(vistaListas);
        vistaListas.setVisible(true);
        centrarVentana(vistaListas);
    }//GEN-LAST:event_mnuItemListadosActionPerformed

    private void masajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masajistaActionPerformed
        VistaMasajista vistaMasajista = new VistaMasajista();
        jDesktop.add(vistaMasajista);
        vistaMasajista.setVisible(true);
        centrarVentana(vistaMasajista);    }//GEN-LAST:event_masajistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpaRelax().setVisible(true);
            }
        });
    }

    // Centra los internal frame
    private void centrarVentana(javax.swing.JInternalFrame vista) {
        int x = (jDesktop.getWidth() - vista.getWidth()) / 2;
        int y = (jDesktop.getHeight() - vista.getHeight()) / 2;
        vista.setLocation(new java.awt.Point(x, y));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem consultorios;
    private javax.swing.JMenuItem formSesion;
    private javax.swing.JMenuItem instalacion;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemDiaSpa;
    private javax.swing.JMenuItem masajista;
    private javax.swing.JMenu menCliente;
    private javax.swing.JMenu menConsultorios;
    private javax.swing.JMenu menDiaDeSpa;
    private javax.swing.JMenu menInstalacion;
    private javax.swing.JMenu menListados;
    private javax.swing.JMenu menMasajista;
    private javax.swing.JMenu menSesion;
    private javax.swing.JMenu menTratamiento;
    private javax.swing.JMenuItem mnuItemListados;
    private javax.swing.JMenuItem tratamiento;
    // End of variables declaration//GEN-END:variables
}
