/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Consultorio;
import Modelo.DiaDeSpa;
import Modelo.Instalacion;
import Modelo.Masajista;
import Modelo.Sesion;
import Modelo.Tratamiento;
import Persistencia.ConsultorioData;
import Persistencia.DiadeSpaData;
import Persistencia.InstalacionData;
import Persistencia.MasajistaData;
import Persistencia.SesionData;
import Persistencia.TratamientoData;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VistaSesion extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private DiadeSpaData diaSpaData;
    private MasajistaData masajData;
    private TratamientoData tratData;
    private InstalacionData instData;
    private ConsultorioData consData;
    private SesionData sesionData;

    public VistaSesion() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modelo = new DefaultTableModel();
        sesionData = new SesionData();
        diaSpaData = new DiadeSpaData();
        masajData = new MasajistaData();
        tratData = new TratamientoData();
        instData = new InstalacionData();
        consData = new ConsultorioData();
        cargarComboHorarios();
        cargarComboPacks();
        cargarComboMasajistas();
        cargarComboTratamientos();
        cargarComboInstalaciones();
        cargarComboConsultorio();
        armarCabeceraTabla();
        cargarComboDuracion();
        limpiarCombos();
        btnActualizar.setEnabled(false);
        btnAlta.setEnabled(false);
        btnBaja.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selecFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbMasajista = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbTratamiento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbConsultorio = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbInstalacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbPack = new javax.swing.JComboBox<>();
        cmbHora = new javax.swing.JComboBox<>();
        chekEstado = new javax.swing.JCheckBox();
        btnInsertar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSesion = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbDuracion = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)15));
        jLabel1.setText("Hora:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Sesión");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel5.setText("Tratamiento:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel6.setText("Masajista:");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel7.setText("Consultorio:");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel8.setText("Instalación:");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel9.setText("Pack:");

        chekEstado.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        chekEstado.setText("Estado");

        btnInsertar.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnBuscar.setText("Buscar por Código");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblSesion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSesion);

        btnActualizar.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnActualizar.setText("Actualizar");

        btnAlta.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnAlta.setText("Alta");

        btnBaja.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnBaja.setText("Baja");

        btnEliminar.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnEliminar.setText("Eliminar");

        btnLimpiar.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel10.setText("Duración:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 717, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(271, 271, 271))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(34, 34, 34)
                                        .addComponent(cmbMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selecFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(14, 14, 14)
                                                .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbPack, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chekEstado)
                                            .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlta)
                                .addGap(18, 18, 18)
                                .addComponent(btnBaja)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cmbMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(cmbConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chekEstado)
                            .addComponent(jLabel10)
                            .addComponent(cmbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(selecFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnInsertar)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        LocalDate fecha;
        LocalTime hora = null;
        LocalDateTime fechaHora;
        LocalDateTime fechaHoraFin;
        String horaString;
        Masajista masajista;
        Tratamiento tratamiento;
        Consultorio consultorio;
        Instalacion instalacion;
        DiaDeSpa diaSpa = null;
        boolean estado = false;
        Sesion sesion;

        diaSpa = (DiaDeSpa) cmbPack.getSelectedItem();
        if (diaSpa == null) {
            JOptionPane.showMessageDialog(this, "Seleccionar un día de spa");
            return;
        }

        if (selecFecha.getDate() != null) {
            fecha = selecFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccionar la fecha");
            return;
        }

        horaString = (String) cmbHora.getSelectedItem();
        if (horaString == null || horaString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccionar la hora");
            return;
        }
        hora = LocalTime.parse(horaString);

        fechaHora = LocalDateTime.of(fecha, hora);

        masajista = (Masajista) cmbMasajista.getSelectedItem();
        tratamiento = (Tratamiento) cmbTratamiento.getSelectedItem();
        consultorio = (Consultorio) cmbConsultorio.getSelectedItem();
        instalacion = (Instalacion) cmbInstalacion.getSelectedItem();

        int duracionMinutos;

        if (tratamiento != null) {
            duracionMinutos = tratamiento.getDuracion();
            if (masajista == null || consultorio == null) {
                JOptionPane.showMessageDialog(this, "Seleccionar Masajista y Consultorio");
                return;
            }
        } else if (instalacion != null) {
            String duracionString = (String) cmbDuracion.getSelectedItem();
            if (duracionString == null || duracionString.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Seleccionar la duración de la instalación");
                return;
            }
            try {
                duracionMinutos = Integer.parseInt(duracionString);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Duración inválida");
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar un Tratamiento con masajista y consultorio o una Instalación");
            return;
        }

        fechaHoraFin = fechaHora.plusMinutes(duracionMinutos);

        estado = chekEstado.isSelected();

        sesion = new Sesion(fechaHora, fechaHoraFin, masajista, tratamiento, consultorio, diaSpa, instalacion, estado);

        try {
            sesionData.insertarSesion(sesion);
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el Día de Spa ");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
        borrarFilaTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        int codigo = 0;

        try {
            codigo = Integer.parseInt(txtBuscar.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese solo numeros");
            return;
        }

        if (codigo <= 0) {
            JOptionPane.showMessageDialog(this, "Código inválido");
            return;
        }

        borrarFilaTabla();

        Sesion sesion = sesionData.buscarSesion(codigo);

        if (sesion == null) {
            JOptionPane.showMessageDialog(this, "No se encontró sesión con ese código");
            limpiarCampos();
            return;
        }

        if (sesion != null) {

            Object codSesion = sesion.getCodSesion();
            Object inicio = sesion.getFechaHoraInicio();
            Object fin = sesion.getFechaHoraFin();

            Object masajista;
            if (sesion.getMasajista() != null) {
                masajista = sesion.getMasajista().getNombre_apellido();
            } else {
                masajista = "-";
            }

            Object tratamiento;
            if (sesion.getTratamiento() != null) {
                tratamiento = sesion.getTratamiento().getNombre();
            } else {
                tratamiento = "-";
            }

            Object consultorio;
            if (sesion.getConsultorio() != null) {
                consultorio = sesion.getConsultorio().getNroConsultorio();
            } else {
                consultorio = "-";
            }

            Object instalacion;
            if (sesion.getInstalacion() != null) {
                instalacion = sesion.getInstalacion().getNombre();
            } else {
                instalacion = "-";
            }

            Object pack;
            if (sesion.getDiaDeSpa() != null) {
                pack = sesion.getDiaDeSpa().getCodPack();
            } else {
                pack = "-";
            }

            Object estado;
            if (sesion.isEstado()) {
                estado = "Activa";
            } else {
                estado = "Inactiva";
            }

            modelo.addRow(new Object[]{
                codSesion,
                inicio,
                fin,
                masajista,
                tratamiento,
                consultorio,
                instalacion,
                pack,
                estado
            });
        }

        if (sesion.getDiaDeSpa() != null) {
            for (int i = 0; i < cmbPack.getItemCount(); i++) {
                DiaDeSpa d = cmbPack.getItemAt(i);
                if (d.getCodPack() == sesion.getDiaDeSpa().getCodPack()) {
                    cmbPack.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            cmbPack.setSelectedItem(null);
        }

        if (sesion.getTratamiento() != null) {
            for (int i = 0; i < cmbTratamiento.getItemCount(); i++) {
                Tratamiento t = cmbTratamiento.getItemAt(i);
                if (t.getCodTratam() == sesion.getTratamiento().getCodTratam()) {
                    cmbTratamiento.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            cmbTratamiento.setSelectedItem(null);
        }

        if (sesion.getMasajista() != null) {
            for (int i = 0; i < cmbMasajista.getItemCount(); i++) {
                Masajista m = cmbMasajista.getItemAt(i);
                if (m.getMatricula() == sesion.getMasajista().getMatricula()) {
                    cmbMasajista.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            cmbMasajista.setSelectedItem(null);
        }

        if (sesion.getConsultorio() != null) {
            for (int i = 0; i < cmbConsultorio.getItemCount(); i++) {
                Consultorio c = cmbConsultorio.getItemAt(i);
                if (c.getNroConsultorio() == sesion.getConsultorio().getNroConsultorio()) {
                    cmbConsultorio.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            cmbConsultorio.setSelectedItem(null);
        }

        if (sesion.getInstalacion() != null) {
            for (int i = 0; i < cmbInstalacion.getItemCount(); i++) {
                Instalacion ins = cmbInstalacion.getItemAt(i);
                if (ins.getCodInstal() == sesion.getInstalacion().getCodInstal()) {
                    cmbInstalacion.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            cmbInstalacion.setSelectedItem(null);
        }

        chekEstado.setSelected(sesion.isEstado());

        selecFecha.setDate(Date.valueOf(sesion.getFechaHoraInicio().toLocalDate()));
        cmbHora.setSelectedItem(sesion.getFechaHoraInicio().toLocalTime().toString());

        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnBaja.setEnabled(true);
        btnAlta.setEnabled(true);
        btnInsertar.setEnabled(false);


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarComboPacks() {
        List<DiaDeSpa> diasSpa = diaSpaData.listarDiadeSpa();
        cmbPack.removeAllItems();
        for (DiaDeSpa d : diasSpa) {
            cmbPack.addItem(d);
        }
    }

    private void cargarComboMasajistas() {
        List<Masajista> masajistas = masajData.listarMasajistas();
        cmbMasajista.removeAllItems();
        for (Masajista m : masajistas) {
            cmbMasajista.addItem(m);
        }
    }

    private void cargarComboTratamientos() {
        List<Tratamiento> tratamientos = tratData.listarTratamientos();
        cmbTratamiento.removeAllItems();
        for (Tratamiento t : tratamientos) {
            cmbTratamiento.addItem(t);
        }
    }

    private void cargarComboInstalaciones() {
        List<Instalacion> instalaciones = instData.listarInstalaciones();
        cmbInstalacion.removeAllItems();
        for (Instalacion i : instalaciones) {
            cmbInstalacion.addItem(i);
        }
    }

    private void cargarComboConsultorio() {
        List<Consultorio> consultorios = consData.listarConsultorios();
        cmbConsultorio.removeAllItems();
        for (Consultorio c : consultorios) {
            cmbConsultorio.addItem(c);
        }
    }

    private void cargarComboHorarios() {
        List<String> horarios = new ArrayList<>();

        horarios.add("08:00");
        horarios.add("08:30");
        horarios.add("09:00");
        horarios.add("09:30");
        horarios.add("10:00");
        horarios.add("10:30");
        horarios.add("11:00");
        horarios.add("11:30");
        horarios.add("12:00");
        horarios.add("12:30");
        horarios.add("13:00");
        horarios.add("13:30");
        horarios.add("14:00");
        horarios.add("14:30");
        horarios.add("15:00");
        horarios.add("15:30");
        horarios.add("16:00");
        horarios.add("16:30");
        horarios.add("17:00");
        horarios.add("17:30");
        horarios.add("18:00");
        horarios.add("18:30");
        horarios.add("19:00");
        horarios.add("19:30");

        cmbHora.removeAllItems();

        for (String hora : horarios) {
            cmbHora.addItem(hora);
        }
    }

    private void cargarComboDuracion() {
        List<String> duraciones = new ArrayList<>();

        duraciones.add("30");
        duraciones.add("60");
        duraciones.add("90");
        duraciones.add("120");

        cmbDuracion.removeAllItems();

        for (String d : duraciones) {
            cmbDuracion.addItem(d);
        }
    }

    private void limpiarCombos() {
        cmbMasajista.setSelectedItem(null);
        cmbTratamiento.setSelectedItem(null);
        cmbConsultorio.setSelectedItem(null);
        cmbInstalacion.setSelectedItem(null);
        cmbPack.setSelectedItem(null);
        cmbDuracion.setSelectedItem(null);
        cmbHora.setSelectedItem(null);

    }

    private void armarCabeceraTabla() {
        List<Object> titulos = new ArrayList<>();

        titulos.add("Código Sesión");
        titulos.add("Inicio");
        titulos.add("Fin");
        titulos.add("Masajista");
        titulos.add("Tratamiento");
        titulos.add("Consultorio");
        titulos.add("Instalación");
        titulos.add("Pack");
        titulos.add("Estado");

        for (Object o : titulos) {
            modelo.addColumn(o);
        }

        tblSesion.setModel(modelo);
    }

    private void borrarFilaTabla() {
        int filas = modelo.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    public void limpiarCampos() {

        cmbPack.setSelectedItem(null);
        cmbTratamiento.setSelectedItem(null);
        cmbMasajista.setSelectedItem(null);
        cmbConsultorio.setSelectedItem(null);
        cmbInstalacion.setSelectedItem(null);
        cmbDuracion.setSelectedItem(null);
        cmbHora.setSelectedItem(null);
        selecFecha.setDate(null);
        chekEstado.setSelected(false);
        txtBuscar.setText("");
        btnActualizar.setEnabled(false);
        btnAlta.setEnabled(false);
        btnBaja.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnInsertar.setEnabled(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chekEstado;
    private javax.swing.JComboBox<Consultorio> cmbConsultorio;
    private javax.swing.JComboBox<String> cmbDuracion;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<Instalacion> cmbInstalacion;
    private javax.swing.JComboBox<Masajista> cmbMasajista;
    private javax.swing.JComboBox<DiaDeSpa> cmbPack;
    private javax.swing.JComboBox<Tratamiento> cmbTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser selecFecha;
    private javax.swing.JTable tblSesion;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
